spring.application.name=cinestar
# Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinestar?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# update  ? atualiza o schema sem apagar dados
# create  ? recria as tabelas ao iniciar
# validate ? só valida, não altera nada
# none    ? desativa o gerenciamento automático
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect